name: Copy release to cloud and update config

on:
  workflow_dispatch:
  push:
    tags:
     - 'v*'

jobs:
  copy_to_cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create cloud branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git branch cloud
          git push origin cloud

      - name: Copy release to cloud
        run: |
          cp -r ${{ github.event.release.tarball_url }} cloud
          git add cloud
          git commit -m "Copy release to cloud"
          git push origin cloud

      - name: Update config
        run: |
          sed -i 's/maxUploadSize = .*/maxUploadSize = 10/' .streamlit/config.toml
          git add .streamlit/config.toml
          git commit -m "Update maxUploadSize to 10"
          git push origin cloud