name: Copy release to cloud and update config

on:
  workflow_dispatch:
  push:
    tags:
     - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Delete cloud branch if exists
        run: |
          git push --delete origin cloud || echo "No cloud branch to delete"
      - name: Create and checkout cloud branch
        run: |
          git checkout -b cloud
          git push -f -u origin cloud
      - name: Modify Streamlit config
        run: |
          sed -i 's/maxUploadSize = .*/maxUploadSize = 10/' .streamlit/config.toml
      - name: Commit changes and push to cloud branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Actions"
          git commit -am "Update Streamlit config"
          git push -u origin cloud
