name: Copy release to cloud and update config

on:
  workflow_dispatch:
  push:
    tags:
     - 'v*'

jobs:
  copy-and-modify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy to Cloud branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b cloud
          git push -u origin cloud
      - name: Modify Config File
        run: |
          sed -i 's/maxUploadSize =.*/maxUploadSize = 10/g' .streamlit/config.toml
          git add .
          git commit -m "Modified streamlit config file"
          git push origin cloud